version: '3'
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: python service.py
    environment:
      - FLASK_APP=service.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./user_service.py:/app/service.py

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    command: python service.py
    environment:
      - FLASK_APP=service.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./product_service.py:/app/service.py

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    command: python service.py
    environment:
      - FLASK_APP=service.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./order_service.py:/app/service.py

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    command: python service.py
    environment:
      - FLASK_APP=service.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./payment_service.py:/app/service.py
